-- Crear la base de datos si no existe
CREATE DATABASE IF NOT EXISTS `votacion`;
USE `votacion`;

-- Tabla de candidatos
CREATE TABLE IF NOT EXISTS `candidatos` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nombre` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Insertar datos en la tabla candidatos
INSERT INTO `candidatos` (`nombre`) VALUES
('Pedro Pérez'),
('María González'),
('Juan Rodríguez'),
('Ana Martínez'),
('Luis García'),
('Laura Sánchez'),
('Diego Fernández'),
('Carla López'),
('José Ramírez'),
('Sofía Torres');

-- Tabla de regiones
CREATE TABLE IF NOT EXISTS `regiones` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nombre` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Insertar datos en la tabla regiones
INSERT INTO `regiones` (`nombre`) VALUES
('Región de Arica y Parinacota'),
('Región de Tarapacá'),
('Región de Antofagasta'),
('Región de Atacama'),
('Región de Coquimbo'),
('Región de Valparaíso'),
('Región Metropolitana de Santiago'),
('Región del Libertador General Bernardo O''Higgins'),
('Región del Maule'),
('Región de Ñuble'),
('Región del Biobío'),
('Región de La Araucanía'),
('Región de Los Ríos'),
('Región de Los Lagos'),
('Región de Aysén del General Carlos Ibáñez del Campo'),
('Región de Magallanes y de la Antártica Chilena');

-- Tabla de comunas
CREATE TABLE IF NOT EXISTS `comunas` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nombre` varchar(255) NOT NULL,
  `region_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `region_id` (`region_id`),
  CONSTRAINT `fk_comunas_region_id` FOREIGN KEY (`region_id`) REFERENCES `regiones` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Insertar datos en la tabla comunas
INSERT INTO `comunas` (`nombre`, `region_id`) VALUES
('Arica', 1),
('Camarones', 1),
('Putre', 1),
('General Lagos', 1),
('Iquique', 2),
('Alto Hospicio', 2),
('Pozo Almonte', 2),
('Huara', 2),
('Camiña', 2),
('Colchane', 2),
('Pica', 2),
('Antofagasta', 3),
('Mejillones', 3),
('Taltal', 3),
('Sierra Gorda', 3),
('Calama', 3),
('Ollagüe', 3),
('San Pedro de Atacama', 3),
('Tocopilla', 3),
('María Elena', 3),
('Copiapó', 4),
('Tierra Amarilla', 4),
('Caldera', 4),
('Chañaral', 4),
('Diego de Almagro', 4),
('Vallenar', 4),
('Huasco', 4),
('Freirina', 4),
('Alto del Carmen', 4),
('La Serena', 5),
('Coquimbo', 5),
('La Higuera', 5),
('Vicuña', 5),
('Paihuano', 5),
('Ovalle', 5),
('Río Hurtado', 5),
('Monte Patria', 5),
('Combarbalá', 5),
('Punitaqui', 5),
('Illapel', 5),
('Canela', 5),
('Salamanca', 5),
('Los Vilos', 5),
('Valparaíso', 6),
('Viña del Mar', 6),
('Concón', 6),
('Quilpué', 6),
('Villa Alemana', 6),
('Limache', 6),
('Olmué', 6),
('Quillota', 6),
('La Calera', 6),
('Nogales', 6),
('Hijuelas', 6),
('La Cruz', 6),
('San Felipe', 6),
('Putaendo', 6),
('Santa María', 6),
('Panquehue', 6),
('Catemu', 6),
('Llay-Llay', 6),
('Los Andes', 6),
('Calle Larga', 6),
('Rinconada', 6),
('San Esteban', 6),
('Quintero', 6),
('Puchuncaví', 6),
('Zapallar', 6),
('Papudo', 6),
('La Ligua', 6),
('Petorca', 6),
('Cabildo', 6),
('San Antonio', 6),
('Santo Domingo', 6),
('Cartagena', 6),
('El Quisco', 6),
('El Tabo', 6),
('Algarrobo', 6),
('Isla de Pascua', 6),
('Juan Fernández', 6),
('Santiago', 7),
('Providencia', 7),
('Las Condes', 7),
('Vitacura', 7),
('La Reina', 7),
('Ñuñoa', 7),
('Macul', 7),
('La Florida', 7),
('Peñalolén', 7),
('La Granja', 7),
('San Joaquín', 7),
('San Miguel', 7),
('Pedro Aguirre Cerda', 7),
('Lo Espejo', 7),
('Cerrillos', 7),
('Maipú', 7),
('Estación Central', 7),
('Pudahuel', 7),
('Lo Prado', 7),
('Quinta Normal', 7),
('Recoleta', 7),
('Independencia', 7),
('Conchalí', 7),
('Huechuraba', 7),
('Quilicura', 7),
('Renca', 7),
('Cerro Navia', 7),
('Lo Barnechea', 7),
('Puente Alto', 7),
('San Bernardo', 7),
('La Cisterna', 7),
('El Bosque', 7),
('San Ramón', 7),
('La Pintana', 7),
('Buin', 7),
('Paine', 7),
('Calera de Tango', 7),
('Peñaflor', 7),
('Padre Hurtado', 7),
('Isla de Maipo', 7),
('Talagante', 7),
('Melipilla', 7),
('Curacaví', 7),
('María Pinto', 7),
('Alhué', 7),
('San Pedro', 7),
('Rancagua', 8),
('Machalí', 8),
('Graneros', 8),
('Codegua', 8),
('Mostazal', 8),
('Requínoa', 8),
('Rengo', 8),
('Olivar', 8),
('Malloa', 8),
('San Vicente', 8),
('Peumo', 8),
('Las Cabras', 8),
('Pichidegua', 8),
('Coltauco', 8),
('Doñihue', 8),
('Coinco', 8),
('Quinta de Tilcoco', 8),
('San Fernando', 8),
('Chimbarongo', 8),
('Placilla', 8),
('Nancagua', 8),
('Santa Cruz', 8),
('Pichilemu', 8),
('Marchigüe', 8),
('Paredones', 8),
('Navidad', 8),
('La Estrella', 8),
('Litueche', 8),
('Talca', 9),
('Curicó', 9),
('Linares', 9),
('Cauquenes', 9),
('Constitución', 9),
('San Javier', 9),
('Molina', 9),
('Sagrada Familia', 9),
('Hualañé', 9),
('Licantén', 9),
('Vichuquén', 9),
('Curepto', 9),
('Pencahue', 9),
('San Clemente', 9),
('Pelarco', 9),
('Río Claro', 9),
('Maule', 9),
('Colbún', 9),
('Yerbas Buenas', 9),
('Retiro', 9),
('Longaví', 9),
('Parral', 9),
('Chanco', 9),
('Pelluhue', 9),
('Chillán', 10),
('Chillán Viejo', 10),
('Bulnes', 10),
('Quillón', 10),
('San Ignacio', 10),
('El Carmen', 10),
('Pemuco', 10),
('Yungay', 10),
('Coihueco', 10),
('San Carlos', 10),
('Ñiquén', 10),
('San Fabián', 10),
('San Nicolás', 10),
('Ninhue', 10),
('Ránquil', 10),
('Quirihue', 10),
('Cobquecura', 10),
('Portezuelo', 10),
('Trehuaco', 10),
('Concepción', 11),
('Talcahuano', 11),
('Hualpén', 11),
('San Pedro de la Paz', 11),
('Chiguayante', 11),
('Coronel', 11),
('Lota', 11),
('Penco', 11),
('Tomé', 11),
('Hualqui', 11),
('Santa Juana', 11),
('Florida', 11),
('Coronel', 11),
('Los Ángeles', 11),
('Mulchén', 11),
('Nacimiento', 11),
('Laja', 11),
('San Rosendo', 11),
('Santa Bárbara', 11),
('Alto Biobío', 11),
('Cabrero', 11),
('Yumbel', 11),
('Monte Aguila', 11),
('Arauco', 11),
('Lebu', 11),
('Curanilahue', 11),
('Los Álamos', 11),
('Cañete', 11),
('Contulmo', 11),
('Tirúa', 11),
('Temuco', 12),
('Padre Las Casas', 12),
('Carahue', 12),
('Cholchol', 12),
('Cunco', 12),
('Curarrehue', 12),
('Freire', 12),
('Galvarino', 12),
('Gorbea', 12),
('Lautaro', 12),
('Loncoche', 12),
('Melipeuco', 12),
('Nueva Imperial', 12),
('Perquenco', 12),
('Pitrufquén', 12),
('Pucón', 12),
('Saavedra', 12),
('Teodoro Schmidt', 12),
('Toltén', 12),
('Vilcún', 12),
('Villarrica', 12),
('Angol', 12),
('Collipulli', 12),
('Ercilla', 12),
('Lonquimay', 12),
('Los Sauces', 12),
('Lumaco', 12),
('Purén', 12),
('Renaico', 12),
('Traiguén', 12),
('Victoria', 12),
('Valdivia', 13),
('Corral', 13),
('Lanco', 13),
('Los Lagos', 13),
('Máfil', 13),
('Mariquina', 13),
('Paillaco', 13),
('Panguipulli', 13),
('La Unión', 13),
('Río Bueno', 13),
('Lago Ranco', 13),
('Futrono', 13),
('Puerto Montt', 14),
('Calbuco', 14),
('Cochamó', 14),
('Maullín', 14),
('Los Muermos', 14),
('Puerto Varas', 14),
('Llanquihue', 14),
('Fresia', 14),
('Frutillar', 14),
('Osorno', 14),
('Purranque', 14),
('Río Negro', 14),
('Puyehue', 14),
('San Pablo', 14),
('San Juan de la Costa', 14),
('Chaitén', 14),
('Futaleufú', 14),
('Hualaihué', 14),
('Palena', 14),
('Ancud', 14),
('Castro', 14),
('Chonchi', 14),
('Curaco de Vélez', 14),
('Dalcahue', 14),
('Puqueldón', 14),
('Queilén', 14),
('Quellón', 14),
('Quemchi', 14),
('Quinchao', 14),
('Coyhaique', 15),
('Lago Verde', 15),
('Aysén', 15),
('Cisnes', 15),
('Guaitecas', 15),
('Chile Chico', 15),
('Río Ibáñez', 15),
('Cochrane', 15),
('O`Higgins', 15),
('Tortel', 15),
('Punta Arenas', 16),
('Puerto Natales', 16),
('Torres del Paine', 16),
('Río Verde', 16),
('Laguna Blanca', 16),
('San Gregorio',16),
('Porvenir',16),
('Primavera',16),
('Timaukel',16),
('Cabo de Hornos',16),
('Antártica',16);


-- Tabla de votantes
CREATE TABLE IF NOT EXISTS `votantes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nombre` varchar(255) NOT NULL,
  `alias` varchar(255) NOT NULL,
  `rut` varchar(20) NOT NULL,
  `email` varchar(255) NOT NULL,
  `region_id` int(11) DEFAULT NULL,
  `comuna_id` int(11) DEFAULT NULL,
  `candidato_id` int(11) DEFAULT NULL,
  `como_se_entero` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_votantes_region_id` (`region_id`),
  KEY `fk_votantes_comuna_id` (`comuna_id`),
  KEY `fk_votantes_candidato_id` (`candidato_id`),
  CONSTRAINT `fk_votantes_region_id` FOREIGN KEY (`region_id`) REFERENCES `regiones` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_votantes_comuna_id` FOREIGN KEY (`comuna_id`) REFERENCES `comunas` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_votantes_candidato_id` FOREIGN KEY (`candidato_id`) REFERENCES `candidatos` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

